# Generated by Django 5.2.7 on 2026-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_team_parent_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('team_lead', 'Team Lead'), ('employee', 'Employee'), ('hr', 'Human Resources'), ('accountant', 'Accountant')], default='employee', max_length=20),
        ),
    ]
