# Generated by Django 5.2.7 on 2026-08-14 21:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_roles(apps, schema_editor):
    Role = apps.get_model("access_control", "Role")
    Membership = apps.get_model("organizations", "OrganizationMembership")
    role_names = {
        "owner": "Owner",
        "admin": "Admin",
        "team_lead": "Team Lead",
        "employee": "Employee",
        "hr": "HR",
        "accountant": "Accountant",
    }

    for membership in Membership.objects.exclude(role__isnull=True):
        code = str(membership.role).lower()
        if code not in role_names:
            code = "employee"
        role, _created = Role.objects.get_or_create(
            code=code,
            defaults={"name": role_names[code], "description": "Migrated Module 1 role"},
        )
        # The legacy column is still a CharField at this migration step.
        # SQLite stores UUID primary keys as 32-character hex strings. Using
        # the same representation also remains valid input for PostgreSQL.
        membership.role = role.pk.hex
        membership.save(update_fields=["role"])


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_remove_legacy_user_permission'),
        ('organizations', '0003_organizationmembership_status_team_leader'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_legacy_roles,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.ForeignKey(blank=True, help_text='RBAC Role assigned to this member within this organization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_memberships', to='access_control.role'),
        ),
    ]
