# Generated by Django 5.2.7 on 2026-08-28 04:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_permission_alter_organizationmembership_role_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('notification_policy_changed', 'Notification Policy Changed')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed payload about what changed (e.g. which permissions were added).')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_org_audits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('target_user', models.ForeignKey(blank=True, help_text='The user who was affected by this action (e.g. granted a role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_org_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Audit Log',
                'verbose_name_plural': 'Organization Audit Logs',
                'db_table': 'organization_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
