# Generated by Django 5.2.7 on 2026-08-31 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organizationmembership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_org_name',
        ),
        migrations.RemoveConstraint(
            model_name='teammembership',
            name='unique_team_membership_user_team',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'name'), name='unique_team_org_name_active'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'team'), name='unique_team_membership_user_team_active'),
        ),
    ]
