# Generated by Django 5.2.7 on 2026-08-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_membership_role_fk_to_access_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembership',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
    ]
