# Generated by Django 5.2.7 on 2026-08-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='dynamic_roles',
            field=models.ManyToManyField(blank=True, help_text='The new permission-based roles assigned to this member.', related_name='memberships', to='organizations.role', verbose_name='Dynamic Roles'),
        ),
    ]
