# Generated by Django on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_seed_system_permissions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='unique_org_membership_user_org',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_role_name_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='teammembership',
            name='unique_team_membership_user_team',
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('user', 'organization'),
                name='unique_active_org_membership_user_org',
            ),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('organization', 'name'),
                name='unique_active_role_name_per_org',
            ),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_deleted', False)),
                fields=('user', 'team'),
                name='unique_active_team_membership_user_team',
            ),
        ),
    ]
