# Generated by Django 5.2.7 on 2026-09-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_partial_unique_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team_org_name',
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'name'), name='unique_team_org_name_active'),
        ),
    ]
