# Generated by Django 5.2.7 on 2026-09-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organizationmembership_unique_active_organization_membership_per_user'),
        ('organizations', '0007_partial_unique_constraints'),
    ]

    operations = [
    ]
