# Generated by Django 5.2.7 on 2026-09-10 04:46

from django.db import migrations

def remove_project_create_from_team_lead(apps, schema_editor):
    Role = apps.get_model('organizations', 'Role')
    Permission = apps.get_model('organizations', 'Permission')

    try:
        project_create_perm = Permission.objects.get(code='project.create')
    except Permission.DoesNotExist:
        return

    team_lead_roles = Role.objects.filter(name='Team Lead')
    for role in team_lead_roles:
        role.permissions.remove(project_create_perm)

def reverse_remove_project_create(apps, schema_editor):
    Role = apps.get_model('organizations', 'Role')
    Permission = apps.get_model('organizations', 'Permission')

    try:
        project_create_perm = Permission.objects.get(code='project.create')
    except Permission.DoesNotExist:
        return

    team_lead_roles = Role.objects.filter(name='Team Lead')
    for role in team_lead_roles:
        role.permissions.add(project_create_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_remove_teammembership_role_team_leader_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_project_create_from_team_lead, reverse_remove_project_create),
    ]
