# Generated by Django 5.2.7 on 2026-09-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20260910_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='salary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount of salary', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('hourly', 'Hourly')], help_text='Type of salary: monthly or hourly', max_length=20, null=True),
        ),
    ]
