# Generated by Django 5.2.7 on 2026-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organizationmembership_salary_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('employee', 'Employee'), ('hr', 'Human Resources'), ('accountant', 'Accountant')], default=None, max_length=20, null=True),
        ),
    ]
