# Generated by Django 5.2.7 on 2026-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0014_delete_hr_and_designer_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="currency",
            field=models.CharField(
                default="IRR",
                help_text="Default currency for the organization",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="salary_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The amount of salary",
                max_digits=20,
                null=True,
            ),
        ),
    ]
