# Generated by Django 5.2.7 on 2026-09-13 11:38

from django.db import migrations


def delete_team_lead_roles(apps, schema_editor):
    Role = apps.get_model('organizations', 'Role')
    Role.objects.filter(name='Team Lead').delete()

class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0015_organization_currency_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_team_lead_roles, reverse_code=migrations.RunPython.noop),
    ]
