# Generated by Django 5.2.7 on 2026-09-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0016_auto_20260913_0438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmembership",
            name="salary_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The amount of salary",
                max_digits=40,
                null=True,
            ),
        ),
    ]
