# Generated by Django 5.2.7 on 2026-09-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_alter_organizationmembership_salary_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationmembership",
            name="salary_amount",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="salary_type",
        ),
    ]
