# Generated by Django 5.2.7 on 2026-09-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_organizationmembership_role'),
        ('organizations', '0018_remove_organizationmembership_salary_amount_and_more'),
    ]

    operations = [
    ]
