# Generated by Django 5.2.7 on 2026-08-07 11:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Enabled')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram Enabled')),
                ('telegram_chat_id', models.CharField(blank=True, help_text='The Telegram user chat ID for sending messages.', max_length=100, null=True, verbose_name='Telegram Chat ID')),
                ('notify_on_task_assigned', models.BooleanField(default=True, verbose_name='Notify on Task Assigned')),
                ('notify_on_task_review', models.BooleanField(default=True, verbose_name='Notify on Task Review')),
                ('notify_on_task_completed', models.BooleanField(default=True, verbose_name='Notify on Task Completed')),
                ('notify_on_mention', models.BooleanField(default=True, verbose_name='Notify on Mention')),
                ('notify_on_deadline', models.BooleanField(default=True, verbose_name='Notify on Deadline Approaching')),
                ('notify_on_leave_updates', models.BooleanField(default=True, verbose_name='Notify on Leave Updates')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
