# Generated by Django 5.2.7 on 2026-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='notify_on_project_created',
            field=models.BooleanField(default=True, verbose_name='Notify on Project Created'),
        ),
    ]
