# Generated by Django 5.2.7 on 2026-08-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_notificationsetting_notify_on_project_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
    ]
