# Generated by Django 5.2.7 on 2026-08-10 11:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0003_delete_notificationsetting'),
        ('projects', '0011_project_prefix_project_unique_project_prefix_per_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, help_text="String identifier for the event trigger (e.g. 'task_completed'). Sent by frontend.", max_length=100)),
                ('action_type', models.CharField(choices=[('telegram', 'Telegram Message'), ('email', 'Email Notification'), ('both', 'Both')], default='telegram', max_length=20)),
                ('telegram_group_id', models.CharField(blank=True, help_text='Telegram Chat ID to send messages to, if action_type is telegram or both.', max_length=255, null=True)),
                ('message_template', models.TextField(help_text='Dynamic message template with {{variables}}.')),
                ('recipients', models.JSONField(blank=True, default=list, help_text="List of recipient roles, e.g. ['owner', 'admins', 'team_leads', 'assignee', 'reporter']")),
                ('project', models.ForeignKey(blank=True, help_text='Project this rule applies to. If null, applies to all organization events.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='projects.project')),
            ],
            options={
                'verbose_name': 'Automation Rule',
                'verbose_name_plural': 'Automation Rules',
                'unique_together': {('project', 'event_type', 'action_type')},
            },
        ),
    ]
