# Generated by Django 5.2.7 on 2026-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_automationrule_optional_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this rule is active and should trigger notifications.'),
        ),
    ]
