# Generated by Django 5.2.7 on 2026-08-10 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0006_automationrule_is_active'),
        ('organizations', '0002_team_parent_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='organization',
            field=models.ForeignKey(help_text='Organization this rule applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='organizations.organization'),
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='project',
        ),
    ]
