# Generated by Django 5.2.7 on 2026-08-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_alter_automationrule_unique_together_and_more'),
        ('organizations', '0002_team_parent_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationrule',
            unique_together={('organization', 'event_type')},
        ),
    ]
