# Generated by Django 5.2.7 on 2026-09-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0008_alter_automationrule_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='recipients',
            field=models.JSONField(blank=True, default=list, help_text="List of recipient roles, e.g. ['owner', 'admins', 'assignee', 'reporter']"),
        ),
    ]
