# Generated by Django 5.2.7 on 2026-09-18 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.JSONField(help_text="JSON format for i18n, e.g. {'en': 'Fast Coder', 'fa': 'کدنویس سریع'}", verbose_name='Name')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='gamification/badges/', verbose_name='Icon')),
                ('is_system_managed', models.BooleanField(default=True, help_text='If true, awarded automatically by system rules.', verbose_name='System Managed')),
                ('points_reward', models.IntegerField(default=0, help_text='Points awarded when this badge is given.', verbose_name='Points Reward')),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.JSONField(help_text='JSON format for i18n', verbose_name='Title')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Description')),
                ('points_reward', models.IntegerField(default=0, verbose_name='Points Reward')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
            },
        ),
        migrations.CreateModel(
            name='BugBounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status')),
                ('awarded_points', models.IntegerField(default=0, verbose_name='Awarded Points')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL, verbose_name='Reporter')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bugs', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Bug Bounty',
                'verbose_name_plural': 'Bug Bounties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('message', models.TextField(verbose_name='Message')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_kudos', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_kudos', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Kudos',
                'verbose_name_plural': 'Kudos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('KUDOS', 'Kudos'), ('QUEST', 'Quest'), ('BUG_BOUNTY', 'Bug Bounty'), ('STORE', 'Reward Store'), ('MANUAL', 'Manual')], max_length=50, verbose_name='Source')),
                ('description', models.JSONField(blank=True, help_text='Translatable JSON description', null=True, verbose_name='Description')),
                ('related_object_id', models.UUIDField(blank=True, null=True, verbose_name='Related Object ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Point Ledger',
                'verbose_name_plural': 'Point Ledgers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPointBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_points', models.IntegerField(default=0, help_text='Lifetime points earned. Used for leaderboards.', verbose_name='Total Points')),
                ('spendable_points', models.IntegerField(default=0, help_text='Points available to spend in the reward store.', verbose_name='Spendable Points')),
                ('kudos_budget', models.IntegerField(default=100, help_text='Monthly budget to thank peers.', verbose_name='Kudos Budget')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_balance', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Point Balance',
                'verbose_name_plural': 'User Point Balances',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to=settings.AUTH_USER_MODEL, verbose_name='Awarded By')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='gamification.badge', verbose_name='Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'badge'), name='unique_active_user_badge')],
            },
        ),
    ]
