# Generated by Django 5.2.7 on 2026-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_status_board_boardcolumn_task_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcolumn',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
