# Generated by Django 5.2.7 on 2026-07-19 08:38

import django.db.models.deletion
import uuid
from django.db import migrations, models

def migrate_statuses(apps, schema_editor):
    TaskStatus = apps.get_model('tasks', 'TaskStatus')
    Task = apps.get_model('tasks', 'Task')

    # Create default statuses
    todo, _ = TaskStatus.objects.get_or_create(code='todo', defaults={'name': 'TODO', 'order': 1})
    doing, _ = TaskStatus.objects.get_or_create(code='doing', defaults={'name': 'Doing', 'order': 2})
    review, _ = TaskStatus.objects.get_or_create(code='review', defaults={'name': 'Review', 'order': 3})
    done, _ = TaskStatus.objects.get_or_create(code='done', defaults={'name': 'Done', 'order': 4})

    status_map = {
        'todo': todo,
        'in_progress': doing,
        'doing': doing,
        'review': review,
        'done': done,
        'blocked': todo,
        'waiting': todo,
    }

    # Update tasks
    for task in Task.objects.all():
        old_val = getattr(task, 'status_old', 'todo')
        new_status = status_map.get(old_val, todo)
        task.status = new_status
        task.save(update_fields=['status'])

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_boardcolumn_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text="Unique identifier for the status (e.g., 'todo', 'doing', 'review')", unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text="Display name for the status (e.g., 'To Do', 'Doing', 'Review')", max_length=100, verbose_name='Name')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='Order in Kanban board columns', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskdependency',
            name='depends_on',
        ),
        migrations.RemoveField(
            model_name='taskdependency',
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskDependency',
        ),
        migrations.AlterUniqueTogether(
            name='boardcolumn',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='boardcolumn',
            constraint=models.UniqueConstraint(fields=('board', 'title'), name='unique_board_column_title'),
        ),
        migrations.AlterModelOptions(
            name='taskactivitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Task Activity Log', 'verbose_name_plural': 'Task Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='taskchecklistitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Task Checklist Item', 'verbose_name_plural': 'Task Checklist Items'},
        ),
        migrations.RemoveField(
            model_name='taskactivitylog',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_status__62d141_idx',
            old_name='tasks_task_status_01b536_idx',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='status_old',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tasks',
                to='tasks.taskstatus',
                verbose_name='Status'
            ),
        ),
        migrations.RunPython(migrate_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tasks',
                to='tasks.taskstatus',
                verbose_name='Status'
            ),
        ),
        migrations.RemoveField(
            model_name='task',
            name='status_old',
        ),
    ]
