# Generated by Django 5.2.7 on 2026-07-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_board_options_board_order_taskstatus_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column',
        ),
        migrations.DeleteModel(
            name='BoardColumn',
        ),
    ]
