# Generated by Django 5.2.7 on 2026-07-24 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_alter_taskcomment_attached_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskcomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Task Comment",
                "verbose_name_plural": "Task Comments",
            },
        ),
        migrations.AddField(
            model_name="task",
            name="progress_cache",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Progress Percent",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AddIndex(
            model_name="taskactivitylog",
            index=models.Index(
                fields=["task", "-created_at"], name="activity_task_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskchecklistitem",
            index=models.Index(
                fields=["task", "is_completed"], name="chk_task_completed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcomment",
            index=models.Index(
                fields=["task", "-created_at"], name="comment_task_created_idx"
            ),
        ),
    ]
