# Generated by Django 5.2.7 on 2026-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_alter_taskcomment_options_task_progress_cache_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="task",
            name="tasks_task_assigne_a1ddb3_idx",
        ),
        migrations.AlterField(
            model_name="task",
            name="progress_cache",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Progress Percent",
            ),
        ),
    ]
