# Generated by Django 5.2.7 on 2026-08-08 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_prefix_project_unique_project_prefix_per_org'),
        ('tasks', '0021_task_is_finished_alter_task_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Task Number'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('project', 'number'), name='unique_task_number_per_project'),
        ),
    ]
