# Generated by Django 5.2.7 on 2026-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_task_number_task_unique_task_number_per_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Blocked'),
        ),
    ]
