# Generated by Django 5.2.7 on 2026-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='code',
            field=models.SlugField(allow_unicode=True, help_text="Identifier for the status (e.g., 'todo', 'doing', 'review')", verbose_name='Code'),
        ),
    ]
