# Generated by Django 5.2.7 on 2026-08-21 20:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_prefix_project_unique_project_prefix_per_org'),
        ('tasks', '0025_alter_taskstatus_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asyncstandup',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Async Standup', 'verbose_name_plural': 'Async Standups'},
        ),
        migrations.RemoveField(
            model_name='asyncstandup',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='asyncstandup',
            name='yesterday_work',
        ),
        migrations.AddField(
            model_name='asyncstandup',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='The working day this standup is reported for.', verbose_name='Standup date'),
        ),
        migrations.AddField(
            model_name='asyncstandup',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of hours worked on this project for the day (0-24).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Hours worked'),
        ),
        migrations.AddField(
            model_name='asyncstandup',
            name='project',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='standups', to='projects.project', verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asyncstandup',
            name='tomorrow_plan',
            field=models.TextField(default='', verbose_name='What will you do tomorrow?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asyncstandup',
            name='today_work',
            field=models.TextField(verbose_name='What did you do today?'),
        ),
        migrations.AddIndex(
            model_name='asyncstandup',
            index=models.Index(fields=['project', 'date'], name='standup_project_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='asyncstandup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'user', 'date'), name='unique_active_standup_project_user_date'),
        ),
    ]
