# Generated by Django 5.2.7 on 2026-08-21 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_asyncstandup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncstandup',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of hours worked on this project for the day.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hours worked'),
        ),
    ]
