# Generated by Django 5.2.7 on 2026-08-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_asyncstandup_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asyncstandup',
            name='tomorrow_plan',
        ),
        migrations.AlterField(
            model_name='asyncstandup',
            name='blockers',
            field=models.TextField(blank=True, null=True, verbose_name='Descriptions and Blockers'),
        ),
        migrations.AlterField(
            model_name='asyncstandup',
            name='today_work',
            field=models.TextField(verbose_name='What did you do today? / What will you do tomorrow?'),
        ),
    ]
