# Generated by Django 5.2.7 on 2026-08-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_remove_asyncstandup_tomorrow_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asyncstandup',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='True if the user has finalized the standup text.', verbose_name='Completed'),
        ),
    ]
