# Generated by Django 5.2.7 on 2026-08-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_asyncstandup_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Estimated Hours'),
        ),
        migrations.AlterField(
            model_name='task',
            name='spent_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hours logged by the assignee', max_digits=10, verbose_name='Spent Hours'),
        ),
    ]
