# Generated by Django 5.2.7 on 2026-09-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_task_estimated_hours_alter_task_spent_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskActivityLog',
        ),
    ]
