# Generated by Django 5.2.7 on 2026-09-10 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_delete_taskactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status_code', models.CharField(blank=True, default='', max_length=50, verbose_name='From status code')),
                ('from_status_name', models.CharField(blank=True, default='', max_length=100, verbose_name='From status name')),
                ('to_status_code', models.CharField(max_length=50, verbose_name='To status code')),
                ('to_status_name', models.CharField(max_length=100, verbose_name='To status name')),
                ('transitioned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Transitioned at')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.taskstatus', verbose_name='From status')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='tasks.task', verbose_name='Task')),
                ('to_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tasks.taskstatus', verbose_name='To status')),
                ('transitioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_transitions', to=settings.AUTH_USER_MODEL, verbose_name='Transitioned by')),
            ],
            options={
                'verbose_name': 'Task Status Transition',
                'verbose_name_plural': 'Task Status Transitions',
                'ordering': ['transitioned_at'],
                'indexes': [models.Index(fields=['task', 'transitioned_at'], name='transition_task_time_idx'), models.Index(fields=['to_status', 'transitioned_at'], name='transition_status_time_idx')],
            },
        ),
    ]
