# Generated by Django 5.2.7 on 2026-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_taskstatus_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='category',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', help_text='Defines the logical behavior of this status (e.g., auto-start timer)', max_length=20, verbose_name='Category'),
        ),
    ]
