# Generated by Django 5.2.7 on 2025-11-25 09:17

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Unique discount code like SUMMER2025', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('percent', models.PositiveIntegerField(help_text='Percentage between 1 and 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount Percentage')),
                ('max_usage', models.PositiveIntegerField(default=1, help_text='Total number of times this code can be used', verbose_name='Max Usage Count')),
                ('current_usage', models.PositiveIntegerField(default=0, editable=False, verbose_name='Current Usage Count')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiration Date')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
