# Generated by Django 5.2.7 on 2026-07-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_discountcode_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='is_deleted',
        ),
    ]
