# Generated by Django 5.2.7 on 2026-07-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_discountcode_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
