# Generated by Django 5.2.7 on 2026-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notify_via_email_user_notify_via_telegram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telegram_connect_token',
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='e.g. @username or username without @', max_length=50, null=True, unique=True, verbose_name='Telegram Username'),
        ),
    ]
