# Generated by Django 5.2.7 on 2026-08-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_telegram_connect_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_language',
            field=models.CharField(default='en', help_text="User's preferred language for Telegram bot (e.g. 'fa', 'en')", max_length=10),
        ),
    ]
