# Generated by Django 5.2.7 on 2026-08-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_set_language_manually',
            field=models.BooleanField(default=False, help_text='True if user explicitly selected language in bot'),
        ),
    ]
