# Generated by Django 5.2.7 on 2026-08-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_has_set_language_manually'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_set_language_manually',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_via_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notify_via_telegram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='workstyleprofile',
            name='has_set_language_manually',
            field=models.BooleanField(default=False, help_text='True if user explicitly selected language in bot'),
        ),
        migrations.AddField(
            model_name='workstyleprofile',
            name='notify_via_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workstyleprofile',
            name='notify_via_telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workstyleprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workstyleprofile',
            name='telegram_language',
            field=models.CharField(default='en', help_text="User's preferred language for Telegram bot (e.g. 'fa', 'en')", max_length=10),
        ),
    ]
