# Generated by Django 5.2.7 on 2026-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_has_set_language_manually_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstyleprofile',
            name='telegram_connect_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
