# Generated by Django 5.2.7 on 2026-09-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_make_first_last_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_preference',
            field=models.CharField(choices=[('gregorian', 'Gregorian'), ('jalali', 'Jalali')], default='gregorian', help_text="User's preferred calendar system", max_length=20),
        ),
    ]
