# Generated by Django 5.2.7 on 2026-10-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_calendar_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='calendar_preference',
            field=models.CharField(choices=[('gregorian', 'Gregorian'), ('jalali', 'Jalali')], default='jalali', help_text="User's preferred calendar system", max_length=20),
        ),
    ]
