# Generated by Django 5.2.7 on 2026-08-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancesession'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timelog',
            name='unique_active_timer_per_user',
        ),
    ]
