# Generated by Django 5.2.7 on 2026-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_timelog_unique_active_timer_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='Timezone'),
        ),
    ]
