# Generated by Django 5.2.7 on 2026-07-19 06:33
# No-op: is_deleted already included in 0001_initial (regenerated on 2026-07-20)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
    ]
