# Generated by Django 5.2.7 on 2026-07-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_attachment_is_deleted_feedback_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='is_deleted',
        ),
    ]
