# Generated by Django 5.2.7 on 2026-07-19 07:25
# No-op: is_deleted already included in 0001_initial (regenerated on 2026-07-20)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_attachment_is_deleted_and_more'),
    ]

    operations = [
    ]
