# Generated by Django 5.2.7 on 2026-07-20 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_expand_project_management_domain"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timeentry",
            name="time_entry_valid_running_state",
        ),
        migrations.AlterField(
            model_name="milestone",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed at"
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="target_date",
            field=models.DateField(verbose_name="Target date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="budget_currency",
            field=models.CharField(
                default="IRR", max_length=3, verbose_name="Budget currency"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed at"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("on_hold", "On hold"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="projectactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("project_created", "Project created"),
                    ("project_updated", "Project updated"),
                    ("member_added", "Member added"),
                    ("member_updated", "Member updated"),
                    ("milestone_updated", "Milestone updated"),
                    ("board_updated", "Board updated"),
                    ("task_updated", "Task updated"),
                    ("standup_submitted", "Standup submitted"),
                ],
                max_length=30,
                verbose_name="Event type",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="allocation_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Allocation end date"
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="allocation_percentage",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Allocation percentage",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="allocation_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Allocation start date"
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Is active"
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed at"
            ),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="due_date",
            field=models.DateField(blank=True, null=True, verbose_name="Due date"),
        ),
        migrations.AlterField(
            model_name="projecttask",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date"),
        ),
        migrations.AddConstraint(
            model_name="timeentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("duration_minutes__isnull", False),
                        ("ended_at__isnull", False),
                        ("is_running", False),
                    ),
                    models.Q(
                        ("ended_at__isnull", True),
                        ("is_running", True),
                        ("started_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="time_entry_valid_running_state",
            ),
        ),
    ]
