# Generated by Django 5.2.7 on 2026-07-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0002_milestone_is_deleted_project_is_deleted_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmember",
            options={
                "ordering": ["project", "user"],
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
            },
        ),
        migrations.RemoveConstraint(
            model_name="projectmember",
            name="unique_project_member",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_org_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="project",
            name="project_owner_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectmember",
            name="member_user_active_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="organization_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner_id",
        ),
        migrations.RemoveField(
            model_name="project",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="projectactivity",
            name="actor_id",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="user_id",
        ),
        migrations.AddField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="organizations.team",
                verbose_name="Team",
            ),
        ),
        migrations.AddField(
            model_name="projectactivity",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actor",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_memberships",
                to="organizations.team",
                verbose_name="Team",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="projectactivity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("project_created", "Project created"),
                    ("project_updated", "Project updated"),
                    ("member_added", "Member added"),
                    ("member_updated", "Member updated"),
                    ("member_removed", "Member removed"),
                    ("milestone_created", "Milestone created"),
                    ("milestone_updated", "Milestone updated"),
                    ("milestone_completed", "Milestone completed"),
                    ("task_created", "Task created"),
                    ("task_updated", "Task updated"),
                    ("task_completed", "Task completed"),
                ],
                max_length=20,
                verbose_name="Entity type",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "status"], name="project_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="project_owner_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectmember",
            index=models.Index(
                fields=["user", "is_active"], name="member_user_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user"), name="unique_project_member"
            ),
        ),
    ]
