# Generated by Django 5.2.7 on 2026-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projectmember_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectactivity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("member", "Member"),
                    ("milestone", "Milestone"),
                    ("task", "Task"),
                ],
                max_length=20,
                verbose_name="Entity type",
            ),
        ),
    ]
