# Generated by Django 5.2.7 on 2026-07-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_fix_entity_type_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectactivity",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("project_created", "Project created"),
                    ("project_updated", "Project updated"),
                    ("project_deleted", "Project deleted"),
                    ("member_added", "Member added"),
                    ("member_updated", "Member updated"),
                    ("member_removed", "Member removed"),
                    ("milestone_created", "Milestone created"),
                    ("milestone_updated", "Milestone updated"),
                    ("milestone_completed", "Milestone completed"),
                    ("milestone_deleted", "Milestone deleted"),
                    ("task_created", "Task created"),
                    ("task_updated", "Task updated"),
                    ("task_completed", "Task completed"),
                ],
                max_length=30,
                verbose_name="Event type",
            ),
        ),
    ]
