# Generated by Django 5.2.7 on 2026-07-27 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_team_parent_team"),
        ("projects", "0005_add_deleted_event_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmember",
            options={
                "ordering": [
                    "project",
                    models.OrderBy(models.F("user"), nulls_last=True),
                ],
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
            },
        ),
        migrations.RemoveConstraint(
            model_name="projectmember",
            name="unique_project_member",
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("project", "user"),
                name="unique_active_project_member",
            ),
        ),
    ]
