# Generated by Django 5.2.7 on 2026-07-27 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_team_parent_team"),
        ("projects", "0006_fix_user_set_null_and_partial_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("user__isnull", True)),
                fields=("project", "team"),
                name="unique_active_project_team",
            ),
        ),
    ]
