# Generated by Django 5.2.7 on 2026-07-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_add_unique_active_project_team_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Weight/Percentage of this milestone in overall project progress (e.g. 1 to 100)",
                verbose_name="Weight",
            ),
        ),
    ]
