# Generated by Django 5.2.7 on 2026-07-27 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_team_parent_team"),
        ("projects", "0008_add_milestone_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
    ]
