# Generated by Django 5.2.7 on 2026-08-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_make_project_org_required"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.AlterField(
            model_name="milestone",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="When work on this milestone begins.",
                null=True,
                verbose_name="Start date",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="target_date",
            field=models.DateField(
                help_text="The expected completion date for this milestone.",
                verbose_name="Target date",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                blank=True,
                help_text="The absolute final date for project completion.",
                null=True,
                verbose_name="Deadline",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="The date when the project officially begins.",
                null=True,
                verbose_name="Start date",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="allocation_end_date",
            field=models.DateField(
                blank=True,
                help_text="When this member stops working on the project. May differ from the project deadline.",
                null=True,
                verbose_name="Allocation end date",
            ),
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="allocation_start_date",
            field=models.DateField(
                blank=True,
                help_text="When this member starts working on the project. May differ from the project start date.",
                null=True,
                verbose_name="Allocation start date",
            ),
        ),
    ]
