# Generated by Django 5.2.7 on 2026-08-08 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_team_parent_team'),
        ('projects', '0010_remove_project_team_alter_milestone_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, help_text='Short identifier for tasks (e.g., MAD)', max_length=10, null=True, verbose_name='Key Prefix'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('prefix__isnull', False)), fields=('organization', 'prefix'), name='unique_project_prefix_per_org'),
        ),
    ]
