# Generated by Django 5.2.7 on 2026-08-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_prefix_project_unique_project_prefix_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color code for project accent (e.g., #6366f1)', max_length=20, verbose_name='Color'),
        ),
    ]
