# Generated by Django 5.2.7 on 2026-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_color_to_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='entity_type',
            field=models.CharField(choices=[('project', 'Project'), ('member', 'Member'), ('milestone', 'Milestone'), ('board', 'Board'), ('task', 'Task')], max_length=20, verbose_name='Entity type'),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_deleted', 'Project deleted'), ('member_added', 'Member added'), ('member_updated', 'Member updated'), ('member_removed', 'Member removed'), ('milestone_created', 'Milestone created'), ('milestone_updated', 'Milestone updated'), ('milestone_completed', 'Milestone completed'), ('milestone_deleted', 'Milestone deleted'), ('board_created', 'Board created'), ('board_updated', 'Board updated'), ('board_deleted', 'Board deleted'), ('status_added', 'Status added'), ('status_removed', 'Status removed'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_completed', 'Task completed'), ('task_deleted', 'Task deleted'), ('task_comment_added', 'Task comment added'), ('task_checklist_updated', 'Task checklist updated')], max_length=30, verbose_name='Event type'),
        ),
    ]
