# Generated by Django 5.2.7 on 2026-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_projectactivity_entity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="salary_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The salary amount for this member in this project.",
                max_digits=20,
                null=True,
                verbose_name="Salary amount",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="salary_override",
            field=models.BooleanField(
                default=False,
                help_text="If True, this project uses a custom salary instead of the organization-level salary. When False, changes to the org-level salary will propagate here automatically.",
                verbose_name="Salary override",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="salary_type",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("hourly", "Hourly")],
                help_text="Type of salary: monthly or hourly. Copied from org membership by default.",
                max_length=20,
                null=True,
                verbose_name="Salary type",
            ),
        ),
    ]
