# Generated by Django 5.2.7 on 2026-09-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_add_salary_fields_to_project_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmember",
            name="salary_amount",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="salary_override",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="salary_type",
        ),
    ]
