name: Web CI

on:
  pull_request:
    paths:
      - "apps/web/**"
      - ".github/workflows/web-ci.yml"
  push:
    branches: [main, develop]

jobs:
  web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          # اینجا بهش می‌گیم که برای هش کردن کش، از فایل لاکِ داخل پوشه وب استفاده کن
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        # با فلگ prefix به npm می‌گیم که عملیات رو داخل پوشه apps/web انجام بده
        run: npm ci --prefix apps/web

      - name: Lint
        run: npm run lint --prefix apps/web

      - name: Build
        run: npm run build --prefix apps/web
        env:
          VITE_API_BASE_URL: /api
          VITE_API_VERSION: v1
          VITE_API_TIMEOUT: "30000"
          VITE_USE_MOCK: "false"
